name: SoutherSavages
favicon: null
layout_spectrum: 1
typography_spectrum: 0.82741
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050505'
    - '#ffffff'
    - '#847b72'
    - '#4f4417'
    - '#b7ada1'
  brandStrength: 0.75
  lightness: 0.5625
  saturation: 0.4375
  rhythmicContrast: 1
purpose: []
