name: Southern Savages
favicon: null
layout_spectrum: 1
typography_spectrum: 0.82741
title: SOUTHERN SAVAGES
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#f3f3f3'
    - '#20343b'
    - '#6c6552'
    - '#a58666'
  brandStrength: 0
  lightness: 0.5625
  saturation: 0.5625
  rhythmicContrast: 0
purpose: []
